app/models.py
from datetime import datetime
from . import db 
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,  primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure = db.Column(db.String(255))

    pitchs = db.relationship('Pitch',backref='user',lazy='dynamic')
    comments = db.relationship('Comment', backref = 'comment', lazy= "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitch'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String())
    category = db.Column(db.String(255))
    
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.relationship('Comment', backref = 'comments', lazy= "dynamic")

    @classmethod
    def get_pitches(cls, category):
        pitches = Pitch.query.filter_by(pitch_category=category).all()
        return pitches

    def __repr__(self):
        return f'{self.title}'

class Comment(db.Model):
    __tablename__='comments'

    id = db.Column(db.Integer,primary_key=True)
    comment_content = db.Column(db.String())
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitch.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

   


    def __repr__(self):
        return f'{self.comment}'          

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField

class PitchForm(FlaskForm):

    title = StringField('Pitch title')
    category= SelectField('Pitch Category', choices=[('Select a category', 'Select a category'),('Business', 'Business'),('Science and Tech', 'Science and Tech'),('Interview Pitch', 'Interview Pitch'),('Maths pitch', 'Maths pitch'),('Pick-up lines', 'Pick-up lines')])
    content = TextAreaField('The pitch...')
    submit = SubmitField('Post')


class CommentForm(FlaskForm):

    comment = TextAreaField('Post Of The Comment')
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us more about you...')
    submit = SubmitField('Submit')

app/__init__.py
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager 
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

bootstrap = Bootstrap()

db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    db.init_app(app)
    bootstrap = Bootstrap(app)
    login_manager.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    # registering the main app blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    return app 

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import Flask
from . import main
from flask_login import login_required
from flask import render_template, redirect, url_for, abort, flash
import datetime
from ..models import User, Pitch, Comment
from .forms import UpdateProfile, PitchForm , CommentForm
from .. import db
app = Flask(__name__)


# views
@main.route("/")
def index():
   '''
   title = "Pitch Perfect"
   '''
  
   title = 'Pitch Perfect'
   pitch=Pitch.query.order_by(Pitch.id.desc()).all()

   return render_template('index.html', title= title,pitch=pitch)

@main.route('/pitch/new', methods=['GET','POST'])
@login_required
def new_pitch():
    form = PitchForm()

    if form.validate_on_submit():

        title=form.title.data
        content=form.content.data
        category=form.category.data
        pitch = Pitch(title=title, content=content,category=category)
        # pitch.save_pitch(pitch)
        db.session.add(pitch)
        db.session.commit()

        flash('Your pitch has been created!', 'success')
        return redirect(url_for('main.index', id=pitch.id))

    return render_template('new_pitch.html', title='New Post', pitch_form=form, post ='New Post')   

@main.route('/comment/new/<int:id>', methods=['GET','POST'])
@login_required
def new_comment(id):
    form = CommentForm()

    if form.validate_on_submit():
        
        comment_content = form.comment.data
        

        comment = Comment(comment_content= comment_content,pitch_id=id)

        # pitch.save_pitch(pitch)
        db.session.add(comment)
        db.session.commit()
        
    comment = Comment.query.filter_by(pitch_id=id).all()
  


    return render_template('new_comment.html', title='New Post', comment=comment,comment_form=form, post ='New Post')

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<head>

</head>
<body>
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    <div class="container">
        {% block content %}

                    

        {% endblock%}
    </div>
</body>   
      

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html'as macros%}
{% block styles%}
    {{ super() }}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    {% endblock %}
    <body>
    {% block content %}
<div class="container-fluid">
    <div  style="background-color:#DDAF94; padding-top: 130px;" class="row">
        
        <div class="col-md-2">
           
       
        </div>
        <div class="col-md-8">
        <a href="{{ url_for('main.new_pitch') }}"><button style="color: black;" class="btn btn-success">Post a pitch</button></a>
            <br>
            
            <br>
            <div>{{macros.displayPitches(pitch)}}</div>
           
                <div style="background-color:#b3d7ef;" class="card">
                    <article class="media content-section">
                        <div class="card-title">
                           
                            <div class="card-body">
                            
                            <h4 style="font-weight: bold;">Category:Business</h4>
                            <small> A business pitch </small>
                            
                            <p> Success is not final; failure is not fatal: it is the courage to continue that counts.</p>
                            <small><a href="#"><button class="btn btn-outline-success btn-sm" id="like"> 
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Bot%C3%B3n_Me_gusta.svg/1200px-Bot%C3%B3n_Me_gusta.svg.png" alt="Upvote" width="30px" height="30px">
                                <!-- <i class="fa fa-heart" id="up"></i> -->
                            </button></a> <p id="name" style="color: white;"></p>  <a href="#"><button class="btn btn-outline-warning btn-sm" id="dislike">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS74bhuasj_h106Bm11-0bx4sNEUSmVc16dHA&usqp=CAU" alt="Downvote" width="30px" height="30px"> </button>
                            <p id="mane" style="color: white;"></p></a></small>
                            <br>
                         
                            <div><a href=""> <button class="btn btn-outline-info btn-sm" id="comment">Comment</button> </a> </div>
                            
                            </div>
                            
                        </div>
                    </article>
                </div>   
                <br>
                <div style="background-color:#b3d7ef;" class="card">
                    <article class="media content-section">
                        <div class="card-title">
                           
                            <div class="card-body">
                            
                            <h4 style="font-weight: bold;">Category:Science &Tech</h4>
                            <small> A science tech pitch </small>
                            
                            <p> Any sufficiently advanced technology is indistinguishable from magic.</p>
                            <small><a href="#"><button class="btn btn-outline-success btn-sm" id="like"> 
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Bot%C3%B3n_Me_gusta.svg/1200px-Bot%C3%B3n_Me_gusta.svg.png" alt="Upvote" width="30px" height="30px">
                                <!-- <i class="fa fa-heart" id="up"></i> -->
                            </button></a> <p id="name" style="color: white;"></p>  <a href="#"><button class="btn btn-outline-warning btn-sm" id="dislike">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS74bhuasj_h106Bm11-0bx4sNEUSmVc16dHA&usqp=CAU" alt="Downvote" width="30px" height="30px"> </button>
                            <p id="mane" style="color: white;"></p></a></small>
                            <br>
                          
                           
                            </div>
                            
                        </div>
                    </article>
                </div>  
                <br>
               
              
        </div>
     
    </div>

    
</div>  
<script type="text/javascript">
$(document).ready(function(){
    var like=0
    var dislike=0
    $("#like").click(function(){
        like++;
        document.getElementById("name").innerHTML=like

});
$("#dislike").click(function(){
        dislike++;
        document.getElementById("mane").innerHTML=dislike

});
    
})

</script>
{% endblock  %}
    </body>

app/templates/macros.html
{% macro displayPitches(list) %}
{% for pitch in list %}

<div style="background-color:#b3d7ef;" class="card">
    <article class="media content-section">
        <div class="card-title">
            <div class="article-metadata">
             
            </div>
            <div class="card-body">
            
            <h4 >Category: {{ pitch.category }}</h4>
            <small style="font-size: larger;"> {{ pitch.title }} </small>
            
            <p style="font-size: larger;"> {{ pitch.content }}</p>
            <small><a href="#"><button class="btn btn-outline-success btn-sm" id="like"> 
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Bot%C3%B3n_Me_gusta.svg/1200px-Bot%C3%B3n_Me_gusta.svg.png" alt="Upvote" width="10px" height="10px">
        </button></a> <p id="name" style="color: white;"></p>  <a href="#"><button class="btn btn-outline-warning btn-sm" id="dislike">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS74bhuasj_h106Bm11-0bx4sNEUSmVc16dHA&usqp=CAU" alt="Downvote" width="10px" height="10px"> </button>
            <!-- <small><a href="#"><button class="btn btn-outline-success btn-sm"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Symbol_thumbs_up.svg/765px-Symbol_thumbs_up.svg.png" height="20px"></button></a>  <a href="#"><button class="btn btn-outline-warning btn-sm"> <img src="https://vignette.wikia.nocookie.net/candy-crush-jelly/images/2/2f/Thumbs-down-icon.png/revision/latest?cb=20151226072412" height="20px"></button></a></small> -->
            <br>
            <br>
            <div><a href="{{ url_for('main.new_comment',id=pitch.id) }}"> <button class="btn btn-outline-info btn-sm">Comment</button> </a> </div>
            
            </div>
            <br>
        </div>
    </article>
    
</div>   
<br>
<script type="text/javascript">
    $(document).ready(function(){
        var like=0
        var dislike=0
        $("#like").click(function(){
            like++;
            document.getElementById("name").innerHTML=like
    
    });
    $("#dislike").click(function(){
            dislike++;
            document.getElementById("mane").innerHTML=dislike
    
    });
        
    })
    
    </script>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
{% extends 'base.html'%}

{% block navbar %}

<div style="overflow: hidden; background-color: #333; position: fixed; z-index: 1; top: 0; width: 100%; height: 20%;" class="container-fluid">
    <nav style="overflow: hidden;  height: 100%;" class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"> <img src="https://vignette.wikia.nocookie.net/doblaje/images/b/b9/Pitch-perfect-50cbd4a0c068e.png/revision/latest?cb=20150927051907&path-prefix=es" height="100px"> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav mr-auto" style="padding: 3%;">
        <li class="nav-item active">
            <a style="color:yellow;" class="nav-link" href="/">Home </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#"></a>
        </li>
        <div>
            {% if current_user.is_authenticated %}
                    
            <li><a style="color: yellowgreen;" href="" class="nav-link">{{current_user.username}}</a></li>
            <li><a style="color: yellowgreen;" class="nav-link" href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a style="color: yellowgreen; " class="nav-link" href="{{url_for('auth.login')}}">Sign in</a></li>
            {% endif%}
        </div>
       
        </ul>
        
    </div>
    </nav>
</div>


{% endblock navbar %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container-fluid">
    <div  style="background-color:#deeef9; padding-bottom: 130px; padding-top: 130px;" class="row">
            <div class="container">
                <div class="row">
                    <div class="col-md-2"> 
                        <a href="/"><img src="https://www.logolynx.com/images/logolynx/52/52c91a3ad83f2025fae1cc9755ebc6a2.png" height="70px"> </a>
                    </div>
                    <div style="color:white; background-image: url(https://static.makeuseof.com/wp-content/uploads/2012/02/Ying-and-Yang.png);" class="col-md-8">

                        {{ wtf.quick_form(comment_form) }}

                    </div>
                    <div class="col-md-2">
                    
                    </div>
                    
                </div>
                <br>
                <br>
            
                <div style="width: 300px;" class="container">
                    {% for comment in comment%}
                    <div class="card">
                        <div class="card-title">
                            Comment {{ comment.username }}
                        </div>
                        <div class="card-body">
                            <li>{{comment.comment_content}}</li>
                        </div>
                        <div class="card-footer">
                            <h6><a href="#"><button class="btn btn-outline-success btn-sm"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Symbol_thumbs_up.svg/765px-Symbol_thumbs_up.svg.png" height="20px"></button></a>  <a href="#"><button class="btn btn-outline-warning btn-sm"> <img src="https://vignette.wikia.nocookie.net/candy-crush-jelly/images/2/2f/Thumbs-down-icon.png/revision/latest?cb=20151226072412" height="20px"></button></a><h6>
                        </div>
                    </div>
                    <br>
                    <br>
                    {% endfor %}
                </div>
            </div>
    </div>
                    
</div>
{% endblock%}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container-fluid">
    <div  style="background-color:#deeef9; padding-bottom: 130px; padding-top: 130px;" class="row">
            <div class="container">
                <div class="row">
                    <div class="col-md-2"> 
                        <a href="/"><img src="https://www.logolynx.com/images/logolynx/52/52c91a3ad83f2025fae1cc9755ebc6a2.png" height="70px"> </a>
                    </div>
                    <div style="color:white; background-image: url(https://static.makeuseof.com/wp-content/uploads/2012/02/Ying-and-Yang.png);" class="col-md-8">

                    {{wtf.quick_form(pitch_form)}}

                    </div>
                    <div class="col-md-2">
                    
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div style="background-color:#deeef9; padding-top: 130px; padding-bottom: 400px;" class="container-fluid">
  <div  class="container">
    <div class="row">

    <!-- displaying  Username-->
      <div class="col-md-4">
      
      {% if user == current_user %}
        <h3> {{user.username| capitalize}} </h3>
      {% endif %}
        <!--Displaying user bio-->
        {% if user.bio %}
          <p> {{user.bio}}</p>
        {% else%}
          <p> {{user.username| capitalize}} has no bio </p>
          {% if user == current_user %}
              <a href="{{url_for('main.update_profile',uname=user.username)}}"><button class="btn btn-outline-info btn-sm">Edit profile</button></a>
          {% endif %}
            
        {% endif %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}"><button class="btn btn-outline-info btn-sm">Edit profile</button></a>
      </div>

      <!--Display profile photo-->
            <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img style="border-radius: 10%; " src="{{url_for('static',filename=user.profile_pic_path)}}" alt=""  class="img-circle img-thumbnail">

    {% else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div style="background-color:#deeef9; padding-top: 130px; padding-bottom: 400px;" class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-1">

            </div>
            <div class="col-md-10">
                {{wtf.quick_form(form)}}
            </div>
            <div class="col-md-1">
            
            </div>
        </div>
    
    </div>
</div>
{% endblock %}